-- Internal durable records use native UUID columns. Target/profile/model/catalog
-- identifiers remain text because they are human-declared configuration keys.
-- Existing values must already be UUID-shaped: prior ARL generators emitted UUID strings.

alter table campaign_step_run drop constraint fk_campaign_step_run_campaign;
alter table campaign_step_run drop constraint fk_campaign_step_run_experiment;
alter table experiment_run drop constraint fk_experiment_run_campaign;
alter table experiment_run drop constraint fk_experiment_run_campaign_step;
alter table experiment_run drop constraint fk_experiment_run_planned_spec;
alter table experiment_run drop constraint fk_experiment_run_pre_manifest;
alter table experiment_run drop constraint fk_experiment_run_post_manifest;
alter table experiment_run drop constraint fk_experiment_run_baseline;
alter table planned_run_spec drop constraint fk_planned_run_spec_risk;
alter table experiment_action drop constraint fk_experiment_action_run;
alter table experiment_resource drop constraint fk_experiment_resource_run;
alter table experiment_evidence drop constraint fk_experiment_evidence_run;
alter table evidence_artifact drop constraint fk_evidence_artifact_run;
alter table run_manifest drop constraint fk_run_manifest_spec;
alter table analysis_run drop constraint fk_analysis_run_experiment;
alter table analysis_run drop constraint fk_analysis_run_dataset;
alter table analysis_run drop constraint fk_analysis_run_target_test_batch;
alter table analysis_finding drop constraint fk_analysis_finding_run;
alter table analysis_recommendation drop constraint fk_analysis_recommendation_run;
alter table analysis_dataset drop constraint fk_analysis_dataset_experiment;
alter table analysis_dataset drop constraint fk_analysis_dataset_target_test_batch;
alter table analysis_comparison drop constraint fk_analysis_comparison_experiment;
alter table analysis_comparison drop constraint fk_analysis_comparison_dataset;
alter table analysis_comparison drop constraint fk_analysis_comparison_target_test_batch;
alter table analysis_comparison_run drop constraint fk_analysis_comparison_run_comparison;
alter table analysis_comparison_run drop constraint fk_analysis_comparison_run_analysis;
alter table analysis_ground_truth drop constraint fk_analysis_ground_truth_dataset;
alter table analysis_evaluation drop constraint fk_analysis_evaluation_run;
alter table analysis_evaluation drop constraint fk_analysis_evaluation_ground_truth;
alter table target_test_batch_item drop constraint fk_target_test_batch_item_batch;
alter table multi_agent_analysis drop constraint fk_multi_agent_analysis_run;
alter table agent_step_run drop constraint fk_agent_step_run_analysis;
alter table llm_invocation drop constraint fk_llm_invocation_step;
alter table follow_up_suggestion_run drop constraint fk_follow_up_suggestion_run_analysis;
alter table follow_up_suggestion_run drop constraint fk_follow_up_suggestion_run_batch;
alter table follow_up_test_suggestion drop constraint fk_follow_up_test_suggestion_run;
alter table failure_injection_plan_item drop constraint fk_failure_injection_plan_item_plan;
alter table root_cause_report_run drop constraint fk_root_cause_report_run_analysis;
alter table root_cause_hypothesis drop constraint fk_root_cause_hypothesis_report;
alter table improvement_proposal drop constraint fk_improvement_proposal_report;

alter table campaign_run alter column id type uuid using cast(id as uuid);
alter table campaign_step_run alter column id type uuid using cast(id as uuid);
alter table campaign_step_run alter column campaign_run_id type uuid using cast(campaign_run_id as uuid);
alter table campaign_step_run alter column experiment_run_id type uuid using cast(experiment_run_id as uuid);
alter table risk_assessment alter column id type uuid using cast(id as uuid);
alter table planned_run_spec alter column id type uuid using cast(id as uuid);
alter table planned_run_spec alter column risk_assessment_id type uuid using cast(risk_assessment_id as uuid);
alter table run_manifest alter column id type uuid using cast(id as uuid);
alter table run_manifest alter column planned_run_spec_id type uuid using cast(planned_run_spec_id as uuid);
alter table experiment_definition alter column id type uuid using cast(id as uuid);
alter table experiment_run alter column id type uuid using cast(id as uuid);
alter table experiment_run alter column campaign_run_id type uuid using cast(campaign_run_id as uuid);
alter table experiment_run alter column campaign_step_run_id type uuid using cast(campaign_step_run_id as uuid);
alter table experiment_run alter column planned_run_spec_id type uuid using cast(planned_run_spec_id as uuid);
alter table experiment_run alter column pre_run_manifest_id type uuid using cast(pre_run_manifest_id as uuid);
alter table experiment_run alter column post_run_manifest_id type uuid using cast(post_run_manifest_id as uuid);
alter table experiment_run alter column baseline_experiment_id type uuid using cast(baseline_experiment_id as uuid);
alter table experiment_action alter column id type uuid using cast(id as uuid);
alter table experiment_action alter column experiment_run_id type uuid using cast(experiment_run_id as uuid);
alter table experiment_resource alter column id type uuid using cast(id as uuid);
alter table experiment_resource alter column experiment_run_id type uuid using cast(experiment_run_id as uuid);
alter table experiment_evidence alter column id type uuid using cast(id as uuid);
alter table experiment_evidence alter column experiment_run_id type uuid using cast(experiment_run_id as uuid);
alter table evidence_artifact alter column id type uuid using cast(id as uuid);
alter table evidence_artifact alter column experiment_run_id type uuid using cast(experiment_run_id as uuid);
alter table target_test_batch alter column id type uuid using cast(id as uuid);
alter table target_test_batch_item alter column id type uuid using cast(id as uuid);
alter table target_test_batch_item alter column batch_id type uuid using cast(batch_id as uuid);
alter table analysis_dataset alter column id type uuid using cast(id as uuid);
alter table analysis_dataset alter column experiment_run_id type uuid using cast(experiment_run_id as uuid);
alter table analysis_dataset alter column target_test_batch_id type uuid using cast(target_test_batch_id as uuid);
alter table analysis_run alter column id type uuid using cast(id as uuid);
alter table analysis_run alter column experiment_run_id type uuid using cast(experiment_run_id as uuid);
alter table analysis_run alter column target_test_batch_id type uuid using cast(target_test_batch_id as uuid);
alter table analysis_run alter column analysis_dataset_id type uuid using cast(analysis_dataset_id as uuid);
alter table analysis_finding alter column id type uuid using cast(id as uuid);
alter table analysis_finding alter column analysis_run_id type uuid using cast(analysis_run_id as uuid);
alter table analysis_recommendation alter column id type uuid using cast(id as uuid);
alter table analysis_recommendation alter column analysis_run_id type uuid using cast(analysis_run_id as uuid);
alter table analysis_comparison alter column id type uuid using cast(id as uuid);
alter table analysis_comparison alter column experiment_run_id type uuid using cast(experiment_run_id as uuid);
alter table analysis_comparison alter column target_test_batch_id type uuid using cast(target_test_batch_id as uuid);
alter table analysis_comparison alter column analysis_dataset_id type uuid using cast(analysis_dataset_id as uuid);
alter table analysis_comparison_run alter column analysis_comparison_id type uuid using cast(analysis_comparison_id as uuid);
alter table analysis_comparison_run alter column analysis_run_id type uuid using cast(analysis_run_id as uuid);
alter table analysis_ground_truth alter column id type uuid using cast(id as uuid);
alter table analysis_ground_truth alter column analysis_dataset_id type uuid using cast(analysis_dataset_id as uuid);
alter table analysis_evaluation alter column id type uuid using cast(id as uuid);
alter table analysis_evaluation alter column analysis_run_id type uuid using cast(analysis_run_id as uuid);
alter table analysis_evaluation alter column analysis_ground_truth_id type uuid using cast(analysis_ground_truth_id as uuid);
alter table multi_agent_analysis alter column analysis_run_id type uuid using cast(analysis_run_id as uuid);
alter table agent_step_run alter column id type uuid using cast(id as uuid);
alter table agent_step_run alter column analysis_run_id type uuid using cast(analysis_run_id as uuid);
alter table llm_invocation alter column id type uuid using cast(id as uuid);
alter table llm_invocation alter column agent_step_run_id type uuid using cast(agent_step_run_id as uuid);
alter table follow_up_suggestion_run alter column id type uuid using cast(id as uuid);
alter table follow_up_suggestion_run alter column analysis_run_id type uuid using cast(analysis_run_id as uuid);
alter table follow_up_suggestion_run alter column target_test_batch_id type uuid using cast(target_test_batch_id as uuid);
alter table follow_up_test_suggestion alter column id type uuid using cast(id as uuid);
alter table follow_up_test_suggestion alter column suggestion_run_id type uuid using cast(suggestion_run_id as uuid);
alter table failure_injection_plan alter column id type uuid using cast(id as uuid);
alter table failure_injection_plan_item alter column id type uuid using cast(id as uuid);
alter table failure_injection_plan_item alter column plan_id type uuid using cast(plan_id as uuid);
alter table root_cause_report_run alter column id type uuid using cast(id as uuid);
alter table root_cause_report_run alter column analysis_run_id type uuid using cast(analysis_run_id as uuid);
alter table root_cause_hypothesis alter column id type uuid using cast(id as uuid);
alter table root_cause_hypothesis alter column report_run_id type uuid using cast(report_run_id as uuid);
alter table improvement_proposal alter column id type uuid using cast(id as uuid);
alter table improvement_proposal alter column report_run_id type uuid using cast(report_run_id as uuid);
alter table arl_outbox_job alter column id type uuid using cast(id as uuid);
alter table arl_outbox_job alter column aggregate_id type uuid using cast(aggregate_id as uuid);

alter table campaign_step_run add constraint fk_campaign_step_run_campaign foreign key (campaign_run_id) references campaign_run (id);
alter table campaign_step_run add constraint fk_campaign_step_run_experiment foreign key (experiment_run_id) references experiment_run (id);
alter table experiment_run add constraint fk_experiment_run_campaign foreign key (campaign_run_id) references campaign_run (id);
alter table experiment_run add constraint fk_experiment_run_campaign_step foreign key (campaign_step_run_id) references campaign_step_run (id);
alter table experiment_run add constraint fk_experiment_run_planned_spec foreign key (planned_run_spec_id) references planned_run_spec (id);
alter table experiment_run add constraint fk_experiment_run_pre_manifest foreign key (pre_run_manifest_id) references run_manifest (id);
alter table experiment_run add constraint fk_experiment_run_post_manifest foreign key (post_run_manifest_id) references run_manifest (id);
alter table experiment_run add constraint fk_experiment_run_baseline foreign key (baseline_experiment_id) references experiment_run (id);
alter table planned_run_spec add constraint fk_planned_run_spec_risk foreign key (risk_assessment_id) references risk_assessment (id);
alter table experiment_action add constraint fk_experiment_action_run foreign key (experiment_run_id) references experiment_run (id);
alter table experiment_resource add constraint fk_experiment_resource_run foreign key (experiment_run_id) references experiment_run (id);
alter table experiment_evidence add constraint fk_experiment_evidence_run foreign key (experiment_run_id) references experiment_run (id);
alter table evidence_artifact add constraint fk_evidence_artifact_run foreign key (experiment_run_id) references experiment_run (id);
alter table run_manifest add constraint fk_run_manifest_spec foreign key (planned_run_spec_id) references planned_run_spec (id);
alter table analysis_run add constraint fk_analysis_run_experiment foreign key (experiment_run_id) references experiment_run (id);
alter table analysis_run add constraint fk_analysis_run_dataset foreign key (analysis_dataset_id) references analysis_dataset (id);
alter table analysis_run add constraint fk_analysis_run_target_test_batch foreign key (target_test_batch_id) references target_test_batch (id);
alter table analysis_finding add constraint fk_analysis_finding_run foreign key (analysis_run_id) references analysis_run (id);
alter table analysis_recommendation add constraint fk_analysis_recommendation_run foreign key (analysis_run_id) references analysis_run (id);
alter table analysis_dataset add constraint fk_analysis_dataset_experiment foreign key (experiment_run_id) references experiment_run (id);
alter table analysis_dataset add constraint fk_analysis_dataset_target_test_batch foreign key (target_test_batch_id) references target_test_batch (id);
alter table analysis_comparison add constraint fk_analysis_comparison_experiment foreign key (experiment_run_id) references experiment_run (id);
alter table analysis_comparison add constraint fk_analysis_comparison_dataset foreign key (analysis_dataset_id) references analysis_dataset (id);
alter table analysis_comparison add constraint fk_analysis_comparison_target_test_batch foreign key (target_test_batch_id) references target_test_batch (id);
alter table analysis_comparison_run add constraint fk_analysis_comparison_run_comparison foreign key (analysis_comparison_id) references analysis_comparison (id);
alter table analysis_comparison_run add constraint fk_analysis_comparison_run_analysis foreign key (analysis_run_id) references analysis_run (id);
alter table analysis_ground_truth add constraint fk_analysis_ground_truth_dataset foreign key (analysis_dataset_id) references analysis_dataset (id);
alter table analysis_evaluation add constraint fk_analysis_evaluation_run foreign key (analysis_run_id) references analysis_run (id);
alter table analysis_evaluation add constraint fk_analysis_evaluation_ground_truth foreign key (analysis_ground_truth_id) references analysis_ground_truth (id);
alter table target_test_batch_item add constraint fk_target_test_batch_item_batch foreign key (batch_id) references target_test_batch (id);
alter table multi_agent_analysis add constraint fk_multi_agent_analysis_run foreign key (analysis_run_id) references analysis_run (id);
alter table agent_step_run add constraint fk_agent_step_run_analysis foreign key (analysis_run_id) references analysis_run (id);
alter table llm_invocation add constraint fk_llm_invocation_step foreign key (agent_step_run_id) references agent_step_run (id);
alter table follow_up_suggestion_run add constraint fk_follow_up_suggestion_run_analysis foreign key (analysis_run_id) references analysis_run (id);
alter table follow_up_suggestion_run add constraint fk_follow_up_suggestion_run_batch foreign key (target_test_batch_id) references target_test_batch (id);
alter table follow_up_test_suggestion add constraint fk_follow_up_test_suggestion_run foreign key (suggestion_run_id) references follow_up_suggestion_run (id);
alter table failure_injection_plan_item add constraint fk_failure_injection_plan_item_plan foreign key (plan_id) references failure_injection_plan (id);
alter table root_cause_report_run add constraint fk_root_cause_report_run_analysis foreign key (analysis_run_id) references analysis_run (id);
alter table root_cause_hypothesis add constraint fk_root_cause_hypothesis_report foreign key (report_run_id) references root_cause_report_run (id);
alter table improvement_proposal add constraint fk_improvement_proposal_report foreign key (report_run_id) references root_cause_report_run (id);
